---
  name: My first Git workflow
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch: null
  jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: First workflow
          run: echo "My first workflow using github actions"
          shell: bash
    goodbye:
      runs-on: ubuntu-latest
      steps:
        - name: goodbye
          run: echo "End of my JOB"
          shell: bash
  